language: ruby

rvm:
  - 2.3.1

cache:
  bundler: true

before_install:
  - sed -i 's#https://ruby.taobao.org#https://rubygems.org#' Gemfile Gemfile.lock

install:
  - bundle

script:
  - bundle exec rspec spec --color
  - gem build cant_cant_cant.gemspec

